<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ingredient;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name'             => 'Hat cafe',
                'brand'            => 'Roastery',
                'unit'             => 'kg',
                'stock_quantity'   => 50,
                'unit_price'       => 150000,
                'total_amount'     => 7500000,
                'lot_number'       => 'C001',
                'received_date'    => '2026-04-30',
                'manufacture_date' => '2026-04-10',
                'expiry_date'      => '2026-05-10',
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Matcha premium',
                'brand'            => 'Fuji',
                'unit'             => 'kg',
                'stock_quantity'   => 5,
                'unit_price'       => 2800000,
                'total_amount'     => 14000000,
                'lot_number'       => 'M001',
                'received_date'    => '2026-04-30',
                'manufacture_date' => '2026-04-10',
                'expiry_date'      => '2026-10-10',
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Sirup đâu',
                'brand'            => 'Monin',
                'unit'             => 'chai',
                'stock_quantity'   => 10,
                'unit_price'       => 230000,
                'total_amount'     => 2300000,
                'lot_number'       => 'SRD001',
                'received_date'    => '2026-04-30',
                'manufacture_date' => '2026-04-10',
                'expiry_date'      => '2026-10-10',
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Trà đen',
                'brand'            => 'Phúc Long',
                'unit'             => 'kg',
                'stock_quantity'   => 20,
                'unit_price'       => 240000,
                'total_amount'     => 4800000,
                'lot_number'       => 'TD001',
                'received_date'    => '2026-04-30',
                'manufacture_date' => '2026-04-10',
                'expiry_date'      => '2026-07-07',
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Trà lài',
                'brand'            => 'Cozy',
                'unit'             => 'kg',
                'stock_quantity'   => 20,
                'unit_price'       => 150000,
                'total_amount'     => 3000000,
                'lot_number'       => 'TL001',
                'received_date'    => '2026-04-30',
                'manufacture_date' => '2026-04-10',
                'expiry_date'      => '2026-07-07',
                'is_active'        => true,
                'note'             => null,
            ],
            // --- Nhập kho 05/05/2026 ---
            [
                'name'             => 'Bao bì in logo 1 ly',
                'brand'            => "Eland'orr",
                'unit'             => 'kg',
                'stock_quantity'   => 20,
                'unit_price'       => 50000,
                'total_amount'     => 1000000,
                'purchase_amount'  => 1000000,
                'lot_number'       => 'Bn001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Bao bì in logo 2 ly',
                'brand'            => 'Roastery',
                'unit'             => 'kg',
                'stock_quantity'   => 20,
                'unit_price'       => 60000,
                'total_amount'     => 1200000,
                'purchase_amount'  => 1200000,
                'lot_number'       => 'Bl001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Bột Kem béo',
                'brand'            => 'Zuka',
                'unit'             => 'gói',
                'stock_quantity'   => 30,
                'unit_price'       => 90000,
                'total_amount'     => 2700000,
                'purchase_amount'  => 2700000,
                'lot_number'       => 'KB001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2026-08-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => '1 gói 1 kg',
            ],
            [
                'name'             => 'Hạt cafe',
                'brand'            => 'Roastery',
                'unit'             => 'kg',
                'stock_quantity'   => 50,
                'unit_price'       => 150000,
                'total_amount'     => 7500000,
                'purchase_amount'  => 7500000,
                'lot_number'       => 'C002',
                'received_date'    => '2026-05-04',
                'manufacture_date' => '2026-05-04',
                'expiry_date'      => '2026-11-04',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Ly giấy in logo + nắp (L)',
                'brand'            => "Y'bneth",
                'unit'             => 'cây',
                'stock_quantity'   => 20,
                'unit_price'       => 55000,
                'total_amount'     => 1100000,
                'purchase_amount'  => 1100000,
                'lot_number'       => 'Ll001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Ly giấy in logo + nắp (M)',
                'brand'            => "Y'bneth",
                'unit'             => 'cây',
                'stock_quantity'   => 20,
                'unit_price'       => 52000,
                'total_amount'     => 1040000,
                'purchase_amount'  => 1040000,
                'lot_number'       => 'Lm001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Ly giấy in logo + nắp (S)',
                'brand'            => "Y'bneth",
                'unit'             => 'cây',
                'stock_quantity'   => 20,
                'unit_price'       => 50000,
                'total_amount'     => 1000000,
                'purchase_amount'  => 1000000,
                'lot_number'       => 'Ls001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Muỗng nhựa',
                'brand'            => 'Goverra',
                'unit'             => 'gói',
                'stock_quantity'   => 100,
                'unit_price'       => 20000,
                'total_amount'     => 2000000,
                'purchase_amount'  => 2000000,
                'lot_number'       => 'Mn001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Sữa đặc',
                'brand'            => 'Tulen',
                'unit'             => 'Hộp',
                'stock_quantity'   => 50,
                'unit_price'       => 50000,
                'total_amount'     => 2500000,
                'purchase_amount'  => 2500000,
                'lot_number'       => 'SĐ001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2026-11-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => 'Hộp 1kg',
            ],
            [
                'name'             => 'Whipping Cream',
                'brand'            => 'Wisp',
                'unit'             => 'hộp',
                'stock_quantity'   => 50,
                'unit_price'       => 180000,
                'total_amount'     => 9000000,
                'purchase_amount'  => 9000000,
                'lot_number'       => 'WC001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2026-11-01',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => '1 lít/ hộp bảo quản lạnh 2-6 độ',
            ],
            [
                'name'             => 'Đường cát',
                'brand'            => 'mía lùi',
                'unit'             => 'cây',
                'stock_quantity'   => 5,
                'unit_price'       => 280000,
                'total_amount'     => 1400000,
                'purchase_amount'  => 1400000,
                'lot_number'       => 'Đ001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2026-11-05',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Ống hút giấy lớn',
                'brand'            => "Y'bneth",
                'unit'             => 'gói',
                'stock_quantity'   => 35,
                'unit_price'       => 35000,
                'total_amount'     => 1225000,
                'purchase_amount'  => 1225000,
                'lot_number'       => 'Ôl001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-05',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
            [
                'name'             => 'Ống hút giấy nhỏ',
                'brand'            => "Y'bneth",
                'unit'             => 'gói',
                'stock_quantity'   => 35,
                'unit_price'       => 25000,
                'total_amount'     => 875000,
                'purchase_amount'  => 875000,
                'lot_number'       => 'Ôn001',
                'received_date'    => '2026-05-01',
                'manufacture_date' => '2026-05-01',
                'expiry_date'      => '2027-01-05',
                'minimum_quantity' => 0,
                'is_active'        => true,
                'note'             => null,
            ],
        ];

        foreach ($items as $item) {
            Ingredient::firstOrCreate(['lot_number' => $item['lot_number']], $item);
        }
    }
}
